### ISSUE TITLE
Can't read mmdb from Java MAXMIND api

### ISSUE THREAD

**Issue by DAVIAMERICO242** [sapics/ip-location-db#40]
Code:

```
public class Main {
    public static void main(String[] args) throws IOException, GeoIp2Exception, URISyntaxException {
        File database = new File(Main.class.getClassLoader().getResource("geolite2-city-ipv4.mmdb").getFile());
        DatabaseReader reader = new DatabaseReader.Builder(database).build();
        InetAddress ipAddress = InetAddress.getByName("45.174.188.157");
        CityResponse response = reader.city(ipAddress);

    }
}

```

Issue at line where I build data base:

```
Exception in thread "main" java.lang.UnsupportedOperationException: Invalid attempt to open an unknown database type: city ipv4
	at com.maxmind.geoip2.DatabaseReader.getDatabaseType(DatabaseReader.java:149)
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:113)
	at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:233)
	at org.example.Main.main(Main.java:22)
```

Maven:

```
    <dependencies>
        <dependency>
            <groupId>com.maxmind.geoip2</groupId>
            <artifactId>geoip2</artifactId>
            <version>4.2.0</version>
        </dependency>
    </dependencies>
```

**Comment by sapics** [comment]
Thanks for noticing! I will update README with removing java api.
